spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #cria o banco e atualiza (mantem o banco)
    show-sql: true #mostrar o sql no terminal
    properties:
      hibernate.format_sql: true